In [1]:
import pandas as pd
from sklearn.preprocessing import OrdinalEncoder

In [2]:
# Create Data Frame
df=pd.DataFrame({"Size":["S","M","XL","XXL","L","S","M","XXL","XL","S","S","M","M"]})
df.head()

  Size
0    S
1    M
2   XL
3  XXL
4    L

In [3]:
# define Order Data
Ord_Data=[["S","M","L","XL","XXL"]]

In [4]:
oe = OrdinalEncoder(categories=Ord_Data)

# Fit and transform the data
df["Size_encoded"] = oe.fit_transform(df[["Size"]])
df

   Size  Size_encoded
0     S           0.0
1     M           1.0
2    XL           3.0
3   XXL           4.0
4     L           2.0
5     S           0.0
6     M           1.0
7   XXL           4.0
8    XL           3.0
9     S           0.0
10    S           0.0
11    M           1.0
12    M           1.0